"""Add user since timestamp

Revision ID: 38f944a7ec89
Revises: b7b71c1da203
Create Date: 2018-05-05 20:22:44.411269

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38f944a7ec89'
down_revision = 'b7b71c1da203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_since', sa.DateTime(), nullable=True))
        batch_op.drop_column('member_since')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_since')
        batch_op.add_column(sa.Column('member_since', mysql.DATETIME(), nullable=True))

        # ### end Alembic commands ###
