"""Add edit counter

Revision ID: 3cd66eac7cd6
Revises: 009c842174fe
Create Date: 2017-09-16 13:00:04.066079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd66eac7cd6'
down_revision = '009c842174fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.Integer(), nullable=True))

    with op.batch_alter_table('categories_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.Integer(), autoincrement=False, nullable=True))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.Integer(), nullable=True))
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.Integer(), autoincrement=False, nullable=True))
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('edits')

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True,
               autoincrement=False)
        batch_op.drop_column('edits')

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('edits')

    with op.batch_alter_table('categories_version', schema=None) as batch_op:
        batch_op.drop_column('edits')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('edits')

    # ### end Alembic commands ###
