"""Avatar -> Logo

Revision ID: 3d0b2b0bbbe4
Revises: 38f944a7ec89
Create Date: 2018-05-13 12:50:32.348930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3d0b2b0bbbe4'
down_revision = '38f944a7ec89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column(column_name='avatar_url', type_=sa.String(length=200), new_column_name='logo_url')

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.alter_column(column_name='avatar_url', type_=sa.String(length=200), new_column_name='logo_url')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.alter_column(column_name='logo_url', type_=sa.String(length=200), new_column_name='avatar_url')

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column(column_name='logo_url', type_=sa.String(length=200), new_column_name='avatar_url')

        # ### end Alembic commands ###
