"""empty message

Revision ID: 4e36a15d7c57
Revises: f172984d4569
Create Date: 2017-08-01 22:09:06.023733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e36a15d7c57'
down_revision = 'f172984d4569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tools_version', sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools_version', 'is_active')
    op.drop_column('tools', 'is_active')
    # ### end Alembic commands ###
