"""Add comments

Revision ID: 67372c45e3da
Revises: fdc7ea43cf2a
Create Date: 2018-04-13 21:56:10.069162

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67372c45e3da'
down_revision = 'fdc7ea43cf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: Combine migration scripts
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=500), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('edit_time', sa.DateTime(), nullable=True),
                    sa.Column('deleted', sa.DateTime(), nullable=True),
                    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
                    sa.Column('parent_category_page_id', sa.Integer(), nullable=True),
                    sa.Column('parent_tool_page_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_category_page_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
                    sa.ForeignKeyConstraint(['parent_tool_page_id'], ['tools.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('edits')

    with op.batch_alter_table('categories_version', schema=None) as batch_op:
        batch_op.drop_column('edits')

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('edits')

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.drop_column('edits')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('category_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    op.drop_table('comments')
    # ### end Alembic commands ###
