"""Initial migration

Revision ID: 74c27597b164
Revises: 
Create Date: 2017-09-04 13:26:06.545623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c27597b164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('parent_category_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('what', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('why', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('where', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('edit_msg', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('edit_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('edit_author', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_time_travel_edit', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_categories_version_end_transaction_id'), 'categories_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_categories_version_operation_type'), 'categories_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_categories_version_transaction_id'), 'categories_version', ['transaction_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tools_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('parent_category_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('env', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('project_version', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('link', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('why', sa.String(length=250), autoincrement=False, nullable=True),
    sa.Column('edit_msg', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('edit_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('edit_author', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_time_travel_edit', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_tools_version_end_transaction_id'), 'tools_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_tools_version_operation_type'), 'tools_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_tools_version_transaction_id'), 'tools_version', ['transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(length=500), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('what', sa.String(length=250), nullable=True),
    sa.Column('why', sa.String(length=250), nullable=True),
    sa.Column('where', sa.String(length=250), nullable=True),
    sa.Column('edit_msg', sa.String(length=100), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('edit_author', sa.Integer(), nullable=True),
    sa.Column('is_time_travel_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['edit_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('env', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('project_version', sa.String(length=10), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('why', sa.String(length=250), nullable=True),
    sa.Column('edit_msg', sa.String(length=100), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('edit_author', sa.Integer(), nullable=True),
    sa.Column('is_time_travel_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['edit_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_version_transaction_id'), table_name='tools_version')
    op.drop_index(op.f('ix_tools_version_operation_type'), table_name='tools_version')
    op.drop_index(op.f('ix_tools_version_end_transaction_id'), table_name='tools_version')
    op.drop_table('tools_version')
    op.drop_table('roles')
    op.drop_index(op.f('ix_categories_version_transaction_id'), table_name='categories_version')
    op.drop_index(op.f('ix_categories_version_operation_type'), table_name='categories_version')
    op.drop_index(op.f('ix_categories_version_end_transaction_id'), table_name='categories_version')
    op.drop_table('categories_version')
    # ### end Alembic commands ###
