"""Blocked user bool->timestamp

Revision ID: b7b71c1da203
Revises: 67372c45e3da
Create Date: 2018-04-26 17:42:03.581922

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7b71c1da203'
down_revision = '67372c45e3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_blocked')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('blocked')

        # ### end Alembic commands ###
