"""empty message

Revision ID: ca88e70ef14f
Revises: 
Create Date: 2017-07-03 20:16:33.900585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca88e70ef14f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('parent_category_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('what', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('why', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('where', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('edit_msg', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('edit_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('edit_author', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tools_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('parent_category_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('env', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('created', sa.String(length=25), autoincrement=False, nullable=True),
    sa.Column('project_version', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('link', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('why', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('edit_msg', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('edit_time', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('edit_author', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('what', sa.String(length=200), nullable=True),
    sa.Column('why', sa.String(length=200), nullable=True),
    sa.Column('where', sa.String(length=200), nullable=True),
    sa.Column('edit_msg', sa.String(length=100), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('edit_author', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edit_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('env', sa.String(length=64), nullable=True),
    sa.Column('created', sa.String(length=25), nullable=True),
    sa.Column('project_version', sa.String(length=10), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('why', sa.String(length=200), nullable=True),
    sa.Column('edit_msg', sa.String(length=100), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('edit_author', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edit_author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('tools')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tools_history')
    op.drop_table('roles')
    op.drop_table('categories_history')
    # ### end Alembic commands ###
