"""Add environments table

Revision ID: dced42ca3e74
Revises: 3d0b2b0bbbe4
Create Date: 2018-05-20 14:37:14.534594

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dced42ca3e74'
down_revision = '3d0b2b0bbbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'environments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'tool_environments_version',
        sa.Column('tool_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('environment_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
        sa.Column('operation_type', sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint('tool_id', 'environment_id', 'transaction_id')
    )
    with op.batch_alter_table('tool_environments_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_environments_version_end_transaction_id'), ['end_transaction_id'],
                              unique=False)
        batch_op.create_index(batch_op.f('ix_tool_environments_version_operation_type'), ['operation_type'],
                              unique=False)
        batch_op.create_index(batch_op.f('ix_tool_environments_version_transaction_id'), ['transaction_id'],
                              unique=False)

    op.create_table(
        'tool_environments',
        sa.Column('tool_id', sa.Integer(), nullable=False),
        sa.Column('environment_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
        sa.PrimaryKeyConstraint('tool_id', 'environment_id')
    )

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environments_dumped', sa.String(length=75), nullable=True))
        batch_op.drop_column('env')

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environments_dumped', sa.String(length=75), autoincrement=False, nullable=True))
        batch_op.drop_column('env')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('tools_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('environments_dumped')

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('environments_dumped')

    op.drop_table('tool_environments')
    with op.batch_alter_table('tool_environments_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_environments_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_tool_environments_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_tool_environments_version_end_transaction_id'))

    op.drop_table('tool_environments_version')
    op.drop_table('environments')
    # ### end Alembic commands ###
