"""Change tool created column type to datetime

Revision ID: f9d7021ebb79
Revises: 4e36a15d7c57
Create Date: 2017-08-06 09:43:53.744944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d7021ebb79'
down_revision = '4e36a15d7c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'created',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'created',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
